import type { Drill } from "./types";

/**
 * Drill catalog. Warmups are guided and timed but not recorded.
 * Mains are recorded on camera, uploaded to Drive, and reviewed by Vero.
 * Steps: ≤ 4 lines, ≤ 10 words each. Goldfish rule.
 */
export const DRILLS: Drill[] = [
  // =====================================================================
  // WARMUPS — voice
  // =====================================================================
  {
    id: "w-breath-box",
    phase: "warmup",
    name: "Box breathing",
    skillIds: ["breath", "nerves"],
    minutes: 2,
    steps: ["In for 4. Hold 4. Out 4. Hold 4.", "Four rounds. Hand on belly.", "Then count to 20 on one breath."],
    material: { kind: "none" },
    record: false,
    evalFocus: [],
    intro: "Low breath first. Everything else sits on top of it.",
  },
  {
    id: "w-lip-trill",
    phase: "warmup",
    name: "Lip trills & hum",
    skillIds: ["resonance", "breath"],
    minutes: 2,
    steps: ["Lips loose. Blow a motorboat for 20 seconds.", "Hum 'mmm' until your lips buzz.", "Read the passage feeling that buzz."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "Wake the voice up before you ask it to work.",
  },
  {
    id: "w-siren",
    phase: "warmup",
    name: "The siren",
    skillIds: ["pitch"],
    minutes: 2,
    steps: ["Say 'oooo' from your lowest note to highest, back down.", "Five sirens. Bigger each time.", "Read the passage letting every sentence rise and fall."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "Stretch the range. Melody is what makes people listen.",
  },
  {
    id: "w-high-low",
    phase: "warmup",
    name: "High / low lines",
    skillIds: ["pitch", "tonality"],
    minutes: 3,
    steps: ["Read line one absurdly high.", "Read line two absurdly low.", "Alternate to the end. Feel silly. Good."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "Monotone dies today. Go too far on purpose.",
  },
  {
    id: "w-volume-dial",
    phase: "warmup",
    name: "Volume dial",
    skillIds: ["volume"],
    minutes: 3,
    steps: ["Read the passage at volume 3 of 10.", "Again at 7. This is your new normal.", "Once more at 9. Feel the room fill."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "If you're always quiet, you're never powerful.",
  },
  {
    id: "w-rate-contrast",
    phase: "warmup",
    name: "Rate contrast",
    skillIds: ["rate"],
    minutes: 3,
    steps: ["Sentence one: painfully slow.", "Sentence two: as fast as you can, still clear.", "Alternate through the passage."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "Speed is a dial, not a setting.",
  },
  {
    id: "w-pause-punctuation",
    phase: "warmup",
    name: "Pause on punctuation",
    skillIds: ["pause", "sentence-endings"],
    minutes: 3,
    steps: ["Every comma: one full second of silence.", "Every period: two seconds. Count them.", "It will feel too long. It isn't."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "Silence feels like an eternity to you. Not to them.",
  },
  {
    id: "w-emphasis-shift",
    phase: "warmup",
    name: "Emphasis shift",
    skillIds: ["emphasis"],
    minutes: 2,
    steps: ["Say the line seven times.", "Stress a different word each time.", "Notice how the meaning changes."],
    material: { kind: "line", text: "I didn't say she stole my money." },
    record: false,
    evalFocus: [],
    intro: "One word carries the meaning. Choose it.",
  },
  {
    id: "w-four-emotions",
    phase: "warmup",
    name: "Four emotions",
    skillIds: ["tonality", "facial-expression"],
    minutes: 3,
    steps: ["Read the passage as if thrilled.", "Again as if grieving. Then suspicious.", "Finally tender. Let your face lead."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "Tone lives in the face first.",
  },
  {
    id: "w-archetype-read",
    phase: "warmup",
    name: "Four archetypes",
    skillIds: ["vocal-archetypes"],
    minutes: 3,
    steps: ["Friend: warm, melodic, relaxed.", "Motivator: louder, faster.", "Educator: slower, with pauses.", "Coach: assertive, zero fillers."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "Four voices. You already own them all.",
  },

  // =====================================================================
  // WARMUPS — clarity
  // =====================================================================
  {
    id: "w-face-gym",
    phase: "warmup",
    name: "Articulator gym",
    skillIds: ["articulators"],
    minutes: 2,
    steps: ["Massage the jaw hinge. Yawn wide.", "Tongue circles inside the lips, both ways.", "'Me-may-ma-moh-moo' five times, exaggerated."],
    material: { kind: "none" },
    record: false,
    evalFocus: [],
    intro: "Loose jaw, live tongue. Then we talk.",
  },
  {
    id: "w-pen-read",
    phase: "warmup",
    name: "Pen in mouth",
    skillIds: ["over-articulation", "consonants"],
    minutes: 3,
    steps: ["Bite a pen sideways, gently.", "Read the passage. Fight for every consonant.", "Remove the pen. Read it again. Hear it?"],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "Make it hard now so it's easy later.",
  },
  {
    id: "w-twister-ladder",
    phase: "warmup",
    name: "Twister ladder",
    skillIds: ["tongue-twisters", "articulators"],
    minutes: 3,
    steps: ["Each twister three times: slow, medium, fast.", "Perfect beats fast. Restart if you slip.", "Finish with the whole set at speed."],
    material: { kind: "twisters", count: 4 },
    record: false,
    evalFocus: [],
    intro: "Precision under speed. That's the whole game.",
  },
  {
    id: "w-vowel-stretch",
    phase: "warmup",
    name: "Vowel stretch",
    skillIds: ["vowels"],
    minutes: 2,
    steps: ["Read the passage stretching every vowel.", "Drop the jaw two fingers wide.", "Then read normally. Keep the space."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "Most mumbling is a closed mouth.",
  },
  {
    id: "w-consonant-crunch",
    phase: "warmup",
    name: "Consonant crunch",
    skillIds: ["consonants"],
    minutes: 2,
    steps: ["Read the passage hitting every final consonant.", "'Want', not 'wan'. 'Think', not 'thin'.", "Read again at speed. Keep the endings."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "Endings are where clarity leaks.",
  },
  {
    id: "w-one-breath",
    phase: "warmup",
    name: "One breath, one sentence",
    skillIds: ["fillers", "sentence-endings", "breath"],
    minutes: 3,
    steps: ["Describe your morning, one sentence per breath.", "Inhale only between sentences.", "You can't say 'um' while inhaling."],
    material: { kind: "none" },
    record: false,
    evalFocus: [],
    intro: "The inhale is the filler-killer.",
  },
  {
    id: "w-count-back",
    phase: "warmup",
    name: "Count back by sevens",
    skillIds: ["nerves", "articulators"],
    minutes: 2,
    steps: ["Out loud: 100, 93, 86… for 45 seconds.", "Then one twister, slow and perfect.", "Your brain is now in the room."],
    material: { kind: "twisters", count: 1 },
    record: false,
    evalFocus: [],
    intro: "Get present. Nerves live in the future.",
  },

  // =====================================================================
  // WARMUPS — spontaneity & structure
  // =====================================================================
  {
    id: "w-word-association",
    phase: "warmup",
    name: "Word association",
    skillIds: ["word-association"],
    minutes: 2,
    steps: ["A word appears every 3 seconds.", "Say the first word that comes. Out loud.", "No good answers. Only fast ones."],
    material: { kind: "words", count: 20, intervalSec: 3 },
    record: false,
    evalFocus: [],
    intro: "Turn off the editor in your head.",
  },
  {
    id: "w-yes-and",
    phase: "warmup",
    name: "Yes, and",
    skillIds: ["yes-and"],
    minutes: 3,
    steps: ["A statement appears.", "Say 'Yes, and…' plus one new detail.", "Eight rounds. Escalate every time."],
    material: { kind: "statements", count: 8, intervalSec: 12 },
    record: false,
    evalFocus: [],
    intro: "Accept everything. Add something.",
  },
  {
    id: "w-three-things",
    phase: "warmup",
    name: "Three things",
    skillIds: ["three-two-one", "wheel-60"],
    minutes: 2,
    steps: ["An object appears every 12 seconds.", "Say three things about it. Out loud.", "Six objects. Don't pause to think."],
    material: { kind: "object", count: 6, intervalSec: 12 },
    record: false,
    evalFocus: [],
    intro: "Numbers stop rambling. Three is the number.",
  },
  {
    id: "w-analogy-sprint",
    phase: "warmup",
    name: "Analogy sprint",
    skillIds: ["analogies"],
    minutes: 3,
    steps: ["A concept appears every 15 seconds.", "'X is like…' Finish it out loud.", "Six rounds. Weird is fine."],
    material: { kind: "words", set: "abstract", count: 6, intervalSec: 15 },
    record: false,
    evalFocus: [],
    intro: "The familiar explains the new.",
  },

  // =====================================================================
  // WARMUPS — presence
  // =====================================================================
  {
    id: "w-posture-string",
    phase: "warmup",
    name: "The string",
    skillIds: ["posture"],
    minutes: 2,
    steps: ["Stand. A string pulls from the crown of your head.", "Shoulders down and back. Feet planted.", "Read the passage from this body."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "The body speaks before the mouth.",
  },
  {
    id: "w-power-sphere",
    phase: "warmup",
    name: "Power sphere",
    skillIds: ["gestures"],
    minutes: 3,
    steps: ["Hands between belly button and eyes.", "One gesture on the key word of each sentence.", "Rest hands when silent. Read the passage."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "Gestures are punctuation for the eyes.",
  },
  {
    id: "w-face-expressions",
    phase: "warmup",
    name: "Face gym",
    skillIds: ["facial-expression"],
    minutes: 2,
    steps: ["Exaggerate: happy, sad, surprised, angry. Five times.", "Now read the passage with a moving face.", "Eyebrows do half the work."],
    material: { kind: "passage" },
    record: false,
    evalFocus: [],
    intro: "A still face reads as a dead voice.",
  },
  {
    id: "w-lens-talk",
    phase: "warmup",
    name: "Talk to the lens",
    skillIds: ["eye-contact"],
    minutes: 2,
    steps: ["Cover your self-view. Look only at the lens.", "Tell the lens about your day. 60 seconds.", "The lens is a friend, not a camera."],
    material: { kind: "none" },
    record: false,
    evalFocus: [],
    intro: "Eye contact with a lens is a learnable trick.",
  },
  {
    id: "w-adrenaline",
    phase: "warmup",
    name: "Adrenaline burn",
    skillIds: ["nerves"],
    minutes: 2,
    steps: ["20 jumping jacks or shake everything out.", "Three slow belly breaths.", "Now the nerves are just energy."],
    material: { kind: "none" },
    record: false,
    evalFocus: [],
    intro: "Burn it off before it hijacks you.",
  },

  // =====================================================================
  // MAINS — spontaneity
  // =====================================================================
  {
    id: "m-baseline",
    phase: "main",
    name: "Baseline",
    skillIds: ["wheel-60"],
    minutes: 4,
    steps: ["Spin. 15 seconds to think.", "Talk for 60 seconds. Any structure.", "Vero finds your starting point. No pressure."],
    material: { kind: "topic", set: "easy" },
    prepSeconds: 15,
    speakSeconds: 60,
    minSpeakSeconds: 20,
    record: true,
    evalFocus: ["fillers", "structure", "vocal variety", "presence"],
    intro: "Just talk. I need to see where you are today.",
  },
  {
    id: "m-wheel-60",
    phase: "main",
    name: "60-second wheel",
    skillIds: ["wheel-60", "fillers"],
    minutes: 3,
    steps: ["Spin. 15 seconds of prep.", "Pick one angle. Speak for 60 seconds.", "End on a full sentence."],
    material: { kind: "topic" },
    prepSeconds: 15,
    speakSeconds: 60,
    minSpeakSeconds: 25,
    record: true,
    evalFocus: ["coherence", "fillers", "sentence endings"],
    intro: "One minute on a random topic. Clear and coherent.",
  },
  {
    id: "m-wheel-120-prep",
    phase: "main",
    name: "Two-minute wheel",
    skillIds: ["wheel-120", "prep"],
    minutes: 5,
    steps: ["Spin. One minute to plan with PREP.", "Speak for two minutes.", "Point first. Point last."],
    material: { kind: "topic" },
    frameworkId: "prep",
    prepSeconds: 60,
    speakSeconds: 120,
    minSpeakSeconds: 45,
    record: true,
    evalFocus: ["structure", "coherence", "fillers"],
    intro: "Two minutes with a spine. No wandering.",
  },
  {
    id: "m-wheel-120-cold",
    phase: "main",
    name: "Cold two minutes",
    skillIds: ["no-prep-2min", "wheel-120"],
    minutes: 4,
    steps: ["Spin. Recording starts in 3 seconds.", "Two minutes. Pick any framework as you go.", "Coherent beats clever."],
    material: { kind: "topic", set: "hard" },
    prepSeconds: 3,
    speakSeconds: 120,
    minSpeakSeconds: 45,
    record: true,
    evalFocus: ["structure", "coherence", "fillers", "pace"],
    intro: "No prep. This is how real life works.",
  },
  {
    id: "m-wheel-180-prep5",
    phase: "main",
    name: "Prepared three minutes",
    skillIds: ["wheel-120", "signposting"],
    minutes: 9,
    steps: ["Spin. Five minutes to prepare, no notes on camera.", "Three minutes. Signpost your sections.", "Open and close with the same idea."],
    material: { kind: "topic", set: "hard" },
    frameworkId: "rule-of-three",
    prepSeconds: 300,
    speakSeconds: 180,
    minSpeakSeconds: 60,
    record: true,
    evalFocus: ["structure", "signposting", "engagement"],
    intro: "Prep is allowed. Rambling is not.",
  },
  {
    id: "m-321",
    phase: "main",
    name: "3-2-1 on an object",
    skillIds: ["three-two-one", "wheel-60"],
    minutes: 3,
    steps: ["A random object appears. 10 seconds to think.", "Three steps. Two types. One thing.", "Count out loud as you go."],
    material: { kind: "object" },
    frameworkId: "three-two-one",
    prepSeconds: 10,
    speakSeconds: 75,
    minSpeakSeconds: 25,
    record: true,
    evalFocus: ["framework adherence", "fillers"],
    intro: "Vinh Giang's anti-rambling tool. Use the numbers.",
  },
  {
    id: "m-sell-me-this",
    phase: "main",
    name: "Sell me this",
    skillIds: ["sell-me-this", "problem-solution-benefit"],
    minutes: 3,
    steps: ["An object appears. 20 seconds to think.", "Sell it in 60 seconds.", "Problem, solution, benefit. Then the ask."],
    material: { kind: "object" },
    frameworkId: "problem-solution-benefit",
    prepSeconds: 20,
    speakSeconds: 60,
    minSpeakSeconds: 25,
    record: true,
    evalFocus: ["persuasion", "energy", "structure"],
    intro: "Desire first, features last.",
  },
  {
    id: "m-eli5",
    phase: "main",
    name: "Explain to a five-year-old",
    skillIds: ["explain-simply", "analogies"],
    minutes: 4,
    steps: ["A concept appears. 20 seconds to think.", "60 seconds for a five-year-old.", "Then 60 seconds for an expert. Same concept."],
    material: { kind: "topic", set: "explain" },
    frameworkId: "eli5",
    prepSeconds: 20,
    speakSeconds: 120,
    minSpeakSeconds: 40,
    record: true,
    evalFocus: ["simplicity", "analogies", "clarity"],
    intro: "If you can't say it simply, you don't own it yet.",
  },
  {
    id: "m-expert-interview",
    phase: "main",
    name: "Instant expert",
    skillIds: ["expert-interview", "yes-and"],
    minutes: 4,
    steps: ["You are the world's leading expert on… (it's absurd).", "Three questions, 30 seconds each.", "Total confidence. Make things up with authority."],
    material: { kind: "expert", count: 3, intervalSec: 30 },
    prepSeconds: 5,
    speakSeconds: 100,
    minSpeakSeconds: 40,
    record: true,
    evalFocus: ["confidence", "fluency", "commitment"],
    intro: "Confidence is a decision. Decide.",
  },
  {
    id: "m-devils-advocate",
    phase: "main",
    name: "Devil's advocate",
    skillIds: ["devils-advocate", "prep"],
    minutes: 4,
    steps: ["An opinion appears. Argue the opposite.", "20 seconds to find their best argument.", "90 seconds. Sound like you mean it."],
    material: { kind: "topic", set: "opinion" },
    frameworkId: "prep",
    prepSeconds: 20,
    speakSeconds: 90,
    minSpeakSeconds: 30,
    record: true,
    evalFocus: ["structure", "conviction", "coherence"],
    intro: "Steelman the other side. It sharpens yours.",
  },
  {
    id: "m-bridge",
    phase: "main",
    name: "Bridging",
    skillIds: ["bridge", "add"],
    minutes: 4,
    steps: ["Your message: 'practice beats talent'.", "Three off-topic questions. Bridge each to it.", "'What matters here is…' 40 seconds each."],
    material: { kind: "question", set: "offtopic", count: 3, intervalSec: 40 },
    frameworkId: "bridge",
    prepSeconds: 10,
    speakSeconds: 120,
    minSpeakSeconds: 40,
    record: true,
    evalFocus: ["bridging", "brevity", "composure"],
    intro: "Politicians do this badly. You'll do it well.",
  },

  // =====================================================================
  // MAINS — structure
  // =====================================================================
  {
    id: "m-prep-answer",
    phase: "main",
    name: "PREP an answer",
    skillIds: ["prep", "sentence-endings"],
    minutes: 3,
    steps: ["A question appears. 15 seconds to pick your point.", "Point, reason, example, point. 60 seconds.", "Stop when you land the last point."],
    material: { kind: "question", set: "opinion" },
    frameworkId: "prep",
    prepSeconds: 15,
    speakSeconds: 60,
    minSpeakSeconds: 20,
    record: true,
    evalFocus: ["framework adherence", "sentence endings", "fillers"],
    intro: "The most useful structure you'll ever learn.",
  },
  {
    id: "m-what-so-what",
    phase: "main",
    name: "What / So what / Now what",
    skillIds: ["what-so-what", "so-what"],
    minutes: 3,
    steps: ["A situation appears. 20 seconds to think.", "What happened. Why it matters. What next.", "75 seconds. End with an action."],
    material: { kind: "topic", set: "news" },
    frameworkId: "what-so-what",
    prepSeconds: 20,
    speakSeconds: 75,
    minSpeakSeconds: 25,
    record: true,
    evalFocus: ["framework adherence", "clarity", "action"],
    intro: "Lead people somewhere. Every time.",
  },
  {
    id: "m-psb-pitch",
    phase: "main",
    name: "Problem, solution, benefit",
    skillIds: ["problem-solution-benefit", "so-what"],
    minutes: 4,
    steps: ["Pitch a change you want at work or home.", "30 seconds to think.", "90 seconds. Make the problem hurt first."],
    material: { kind: "story-prompt", set: "pitch" },
    frameworkId: "problem-solution-benefit",
    prepSeconds: 30,
    speakSeconds: 90,
    minSpeakSeconds: 30,
    record: true,
    evalFocus: ["persuasion", "structure", "specificity"],
    intro: "Persuasion has a shape. This is it.",
  },
  {
    id: "m-ppf",
    phase: "main",
    name: "Past, present, future",
    skillIds: ["past-present-future", "wheel-60"],
    minutes: 3,
    steps: ["Spin. 15 seconds.", "Then, now, next. 75 seconds.", "Finish with your own prediction."],
    material: { kind: "topic", set: "abstract" },
    frameworkId: "past-present-future",
    prepSeconds: 15,
    speakSeconds: 75,
    minSpeakSeconds: 25,
    record: true,
    evalFocus: ["framework adherence", "coherence"],
    intro: "Time is a structure nobody gets lost in.",
  },
  {
    id: "m-rule-of-three",
    phase: "main",
    name: "Three things about…",
    skillIds: ["rule-of-three", "signposting"],
    minutes: 3,
    steps: ["Spin. 20 seconds to pick three points.", "Announce three. Number them. Wrap in five words.", "90 seconds."],
    material: { kind: "topic" },
    frameworkId: "rule-of-three",
    prepSeconds: 20,
    speakSeconds: 90,
    minSpeakSeconds: 30,
    record: true,
    evalFocus: ["signposting", "structure", "brevity"],
    intro: "Three is memorable. Four is a list.",
  },
  {
    id: "m-contrast",
    phase: "main",
    name: "Not this, but that",
    skillIds: ["contrast", "precision"],
    minutes: 3,
    steps: ["A question appears. 15 seconds.", "'It's not about X. It's about Y. Because…'", "45 seconds. Sound decisive."],
    material: { kind: "question", set: "opinion" },
    frameworkId: "contrast",
    prepSeconds: 15,
    speakSeconds: 45,
    minSpeakSeconds: 15,
    record: true,
    evalFocus: ["decisiveness", "precision", "brevity"],
    intro: "CEOs answer with contrast. So will you.",
  },
  {
    id: "m-add-qa",
    phase: "main",
    name: "ADD three questions",
    skillIds: ["add", "sentence-endings"],
    minutes: 4,
    steps: ["Three interview questions, 35 seconds each.", "Answer in one sentence. Detail. Describe value.", "Then stop. Silence is fine."],
    material: { kind: "question", set: "interview", count: 3, intervalSec: 35 },
    frameworkId: "add",
    prepSeconds: 5,
    speakSeconds: 105,
    minSpeakSeconds: 30,
    record: true,
    evalFocus: ["brevity", "answer-first", "fillers"],
    intro: "Answer first. Then earn the details.",
  },
  {
    id: "m-golden-circle",
    phase: "main",
    name: "Start with why",
    skillIds: ["golden-circle", "ethos-pathos-logos"],
    minutes: 4,
    steps: ["Pitch something you actually believe in.", "30 seconds to find your why.", "Why, how, what. 90 seconds."],
    material: { kind: "story-prompt", set: "belief" },
    frameworkId: "golden-circle",
    prepSeconds: 30,
    speakSeconds: 90,
    minSpeakSeconds: 30,
    record: true,
    evalFocus: ["conviction", "framework adherence", "energy"],
    intro: "People follow why, not what.",
  },
  {
    id: "m-para-update",
    phase: "main",
    name: "PARA update",
    skillIds: ["para", "precision"],
    minutes: 3,
    steps: ["Give an update on a real project.", "20 seconds to think.", "Point, action, result, ask. 60 seconds."],
    material: { kind: "story-prompt", set: "update" },
    frameworkId: "para",
    prepSeconds: 20,
    speakSeconds: 60,
    minSpeakSeconds: 20,
    record: true,
    evalFocus: ["framework adherence", "brevity", "clear ask"],
    intro: "The update your boss wishes everyone gave.",
  },

  // =====================================================================
  // MAINS — story
  // =====================================================================
  {
    id: "m-story-formula",
    phase: "main",
    name: "Story formula",
    skillIds: ["story-formula", "landing"],
    minutes: 5,
    steps: ["A story prompt appears. 45 seconds to choose a memory.", "Incident. Relive it. 'The reason I'm telling you this…'", "Two minutes max."],
    material: { kind: "story-prompt", set: "personal" },
    frameworkId: "story-formula",
    prepSeconds: 45,
    speakSeconds: 120,
    minSpeakSeconds: 40,
    record: true,
    evalFocus: ["story structure", "reliving", "landing"],
    intro: "Every great speaker has this formula in their bones.",
  },
  {
    id: "m-relive",
    phase: "main",
    name: "Relive, don't report",
    skillIds: ["relive", "vaks"],
    minutes: 5,
    steps: ["Choose a memory. 30 seconds.", "Present tense only. At least two lines of dialogue.", "Two minutes. Be there again."],
    material: { kind: "story-prompt", set: "personal" },
    prepSeconds: 30,
    speakSeconds: 120,
    minSpeakSeconds: 40,
    record: true,
    evalFocus: ["present tense", "dialogue", "sensory detail"],
    intro: "Reporting is dull. Reliving is magnetic.",
  },
  {
    id: "m-vaks",
    phase: "main",
    name: "Four senses",
    skillIds: ["vaks", "story-formula"],
    minutes: 4,
    steps: ["Retell a memory hitting all four senses.", "What you saw, heard, felt, smelled.", "90 seconds. One detail each is enough."],
    material: { kind: "story-prompt", set: "sensory" },
    prepSeconds: 30,
    speakSeconds: 90,
    minSpeakSeconds: 30,
    record: true,
    evalFocus: ["sensory detail", "vividness"],
    intro: "Put them in the room with you.",
  },
  {
    id: "m-hook-five",
    phase: "main",
    name: "Five hooks",
    skillIds: ["hook", "open-strong"],
    minutes: 4,
    steps: ["One story, five openings, 20 seconds each.", "In the action. A question. A bold claim.", "Dialogue. A contrast. Which one wins?"],
    material: { kind: "story-prompt", set: "personal" },
    prepSeconds: 30,
    speakSeconds: 110,
    minSpeakSeconds: 40,
    record: true,
    evalFocus: ["hooks", "variety", "energy"],
    intro: "The first sentence decides if they listen.",
  },
  {
    id: "m-stakes",
    phase: "main",
    name: "Raise the stakes",
    skillIds: ["stakes", "abt"],
    minutes: 5,
    steps: ["A story where something could be lost.", "Say the stakes out loud before the turn.", "And, but, therefore. Two minutes."],
    material: { kind: "story-prompt", set: "stakes" },
    frameworkId: "abt",
    prepSeconds: 40,
    speakSeconds: 120,
    minSpeakSeconds: 40,
    record: true,
    evalFocus: ["stakes", "tension", "structure"],
    intro: "No stakes, no story.",
  },
  {
    id: "m-story-spine",
    phase: "main",
    name: "Story spine",
    skillIds: ["story-spine", "hook"],
    minutes: 5,
    steps: ["A prompt appears. 30 seconds.", "Once upon a time… until one day… because of that…", "Two minutes. Every beat causes the next."],
    material: { kind: "story-prompt", set: "invent" },
    frameworkId: "story-spine",
    prepSeconds: 30,
    speakSeconds: 120,
    minSpeakSeconds: 40,
    record: true,
    evalFocus: ["causality", "structure", "energy"],
    intro: "Pixar's skeleton. Hang anything on it.",
  },
  {
    id: "m-landing",
    phase: "main",
    name: "Stick the landing",
    skillIds: ["landing", "close-strong"],
    minutes: 4,
    steps: ["Tell a short story. 90 seconds.", "End on one lesson in one sentence.", "Then stop. Don't explain the lesson."],
    material: { kind: "story-prompt", set: "lesson" },
    frameworkId: "story-formula",
    prepSeconds: 30,
    speakSeconds: 90,
    minSpeakSeconds: 30,
    record: true,
    evalFocus: ["landing", "brevity", "structure"],
    intro: "The last sentence is the one they keep.",
  },
  {
    id: "m-sparkline",
    phase: "main",
    name: "What is, what could be",
    skillIds: ["sparkline", "monroe"],
    minutes: 5,
    steps: ["Pick a change you want in the world. 40 seconds.", "Alternate reality and possibility three times.", "End on the new bliss. Two minutes."],
    material: { kind: "story-prompt", set: "vision" },
    frameworkId: "sparkline",
    prepSeconds: 40,
    speakSeconds: 120,
    minSpeakSeconds: 40,
    record: true,
    evalFocus: ["contrast", "inspiration", "structure"],
    intro: "This is the shape of every great speech.",
  },
  {
    id: "m-story-bank",
    phase: "main",
    name: "Signature story",
    skillIds: ["story-bank", "story-formula"],
    minutes: 6,
    steps: ["Build one of your five signature stories.", "60 seconds to choose. Two minutes to tell.", "Childhood, failure, win, mentor, turning point."],
    material: { kind: "story-prompt", set: "signature" },
    frameworkId: "story-formula",
    prepSeconds: 60,
    speakSeconds: 150,
    minSpeakSeconds: 45,
    record: true,
    evalFocus: ["story structure", "reliving", "landing", "delivery"],
    intro: "Elite speakers never search for a story. They have five.",
  },
  {
    id: "m-humor-callback",
    phase: "main",
    name: "Plant and pay off",
    skillIds: ["humor-callback", "callbacks"],
    minutes: 5,
    steps: ["Tell a story with one odd detail in the opening.", "Bring it back at the end. Deadpan.", "Two minutes. The callback is the laugh."],
    material: { kind: "story-prompt", set: "funny" },
    prepSeconds: 45,
    speakSeconds: 120,
    minSpeakSeconds: 40,
    record: true,
    evalFocus: ["callback", "timing", "delivery"],
    intro: "Callbacks are the cheapest laugh in comedy.",
  },
  {
    id: "m-vocal-story",
    phase: "main",
    name: "Vocal variety story",
    skillIds: ["rate", "volume", "pitch", "pause"],
    minutes: 4,
    steps: ["Tell a story you know well.", "Exaggerate rate, volume, pitch, and pauses.", "Too much on purpose. 90 seconds."],
    material: { kind: "story-prompt", set: "personal" },
    prepSeconds: 20,
    speakSeconds: 90,
    minSpeakSeconds: 30,
    record: true,
    evalFocus: ["vocal variety", "pauses", "energy"],
    intro: "Overshoot today. Land in the middle tomorrow.",
  },
  {
    id: "m-emphasis-read",
    phase: "main",
    name: "Emphasis on camera",
    skillIds: ["emphasis", "pause", "eye-contact"],
    minutes: 3,
    steps: ["Read the passage to the lens.", "One stressed word per sentence. Pause at every period.", "Look up on the stressed word."],
    material: { kind: "passage" },
    prepSeconds: 20,
    speakSeconds: 75,
    minSpeakSeconds: 25,
    record: true,
    evalFocus: ["emphasis", "pauses", "eye contact"],
    intro: "Reading well is speaking well, slowed down.",
  },

  // =====================================================================
  // MAINS — engagement
  // =====================================================================
  {
    id: "m-analogy-explain",
    phase: "main",
    name: "Explain with analogies",
    skillIds: ["analogies", "explain-simply"],
    minutes: 4,
    steps: ["Three concepts, 30 seconds each.", "Explain each with an analogy, metaphor, or simile.", "'It's like…' is your first sentence."],
    material: { kind: "words", set: "abstract", count: 3, intervalSec: 30 },
    prepSeconds: 10,
    speakSeconds: 90,
    minSpeakSeconds: 30,
    record: true,
    evalFocus: ["analogies", "clarity"],
    intro: "Vinh's AMS drill. Analogy, metaphor, simile.",
  },
  {
    id: "m-so-what-ladder",
    phase: "main",
    name: "So what? ×3",
    skillIds: ["so-what", "what-so-what"],
    minutes: 3,
    steps: ["State a fact about your work or life.", "Answer 'so what?' three times, deeper each time.", "60 seconds. End at the thing they care about."],
    material: { kind: "story-prompt", set: "fact" },
    prepSeconds: 15,
    speakSeconds: 60,
    minSpeakSeconds: 20,
    record: true,
    evalFocus: ["relevance", "depth", "brevity"],
    intro: "Facts are cheap. Meaning is rare.",
  },
  {
    id: "m-rhetoric",
    phase: "main",
    name: "Rhetorical devices",
    skillIds: ["tricolon", "rhetorical-questions"],
    minutes: 4,
    steps: ["Make a 90-second argument.", "Use a tricolon, an anaphora, and an antithesis.", "Ask one rhetorical question. Pause after it."],
    material: { kind: "topic", set: "opinion" },
    prepSeconds: 45,
    speakSeconds: 90,
    minSpeakSeconds: 30,
    record: true,
    evalFocus: ["rhetorical devices", "rhythm", "pauses"],
    intro: "Three beats. Repeat the opening. Flip the contrast.",
  },
  {
    id: "m-open-close",
    phase: "main",
    name: "Open and close only",
    skillIds: ["open-strong", "close-strong"],
    minutes: 3,
    steps: ["Spin a talk topic. 30 seconds.", "30-second opening. Skip the middle.", "30-second close that returns to the opening."],
    material: { kind: "topic", set: "hard" },
    prepSeconds: 30,
    speakSeconds: 60,
    minSpeakSeconds: 20,
    record: true,
    evalFocus: ["hook", "close", "callback"],
    intro: "Nobody remembers the middle.",
  },
  {
    id: "m-monroe",
    phase: "main",
    name: "Motivated sequence",
    skillIds: ["monroe", "ethos-pathos-logos"],
    minutes: 6,
    steps: ["Persuade us to do one thing. 60 seconds prep.", "Attention, need, satisfaction, visualization, action.", "Three minutes. End with the ask."],
    material: { kind: "story-prompt", set: "persuade" },
    frameworkId: "monroe",
    prepSeconds: 60,
    speakSeconds: 180,
    minSpeakSeconds: 60,
    record: true,
    evalFocus: ["persuasion", "structure", "emotion", "call to action"],
    intro: "The persuasion structure behind a thousand speeches.",
  },

  // =====================================================================
  // MAINS — conversation
  // =====================================================================
  {
    id: "m-threading",
    phase: "main",
    name: "Three threads",
    skillIds: ["threading", "anecdotes"],
    minutes: 3,
    steps: ["Answer 'how was your weekend?'", "Offer three threads someone could pull on.", "45 seconds. Specific beats impressive."],
    material: { kind: "question", set: "smalltalk" },
    prepSeconds: 10,
    speakSeconds: 45,
    minSpeakSeconds: 15,
    record: true,
    evalFocus: ["threads offered", "specificity", "warmth"],
    intro: "Small talk dies from one-word answers.",
  },
  {
    id: "m-paraphrase",
    phase: "main",
    name: "Paraphrase",
    skillIds: ["paraphrase", "questions"],
    minutes: 3,
    steps: ["Read the paragraph once. 40 seconds.", "Camera on. Paraphrase it in 30 seconds.", "Start with 'What I'm hearing is…'"],
    material: { kind: "paragraph" },
    prepSeconds: 40,
    speakSeconds: 30,
    minSpeakSeconds: 10,
    record: true,
    evalFocus: ["accuracy", "brevity", "listening"],
    intro: "Listening is a skill you can see.",
  },
  {
    id: "m-anecdote-30",
    phase: "main",
    name: "30-second anecdotes",
    skillIds: ["anecdotes", "hook"],
    minutes: 3,
    steps: ["Three prompts, 30 seconds each.", "One scene, one line of dialogue, one point.", "Stories sized for conversation."],
    material: { kind: "story-prompt", set: "personal", count: 3, intervalSec: 30 },
    prepSeconds: 10,
    speakSeconds: 90,
    minSpeakSeconds: 30,
    record: true,
    evalFocus: ["brevity", "hook", "landing"],
    intro: "Long stories lose rooms. Short ones win them.",
  },
  {
    id: "m-disagree",
    phase: "main",
    name: "Disagree gracefully",
    skillIds: ["disagree", "contrast"],
    minutes: 3,
    steps: ["A statement you disagree with appears.", "Acknowledge, reframe, offer. 45 seconds.", "Warm voice. Firm words."],
    material: { kind: "statements", set: "disagree" },
    frameworkId: "disagree",
    prepSeconds: 15,
    speakSeconds: 45,
    minSpeakSeconds: 15,
    record: true,
    evalFocus: ["tone", "structure", "composure"],
    intro: "Disagreement without heat is a superpower.",
  },
  {
    id: "m-tough-questions",
    phase: "main",
    name: "Tough questions",
    skillIds: ["tough-questions", "bridge"],
    minutes: 4,
    steps: ["Three hostile questions, 35 seconds each.", "Breathe. Answer the fair version.", "Short. Calm. Then stop."],
    material: { kind: "question", set: "hostile", count: 3, intervalSec: 35 },
    frameworkId: "add",
    prepSeconds: 5,
    speakSeconds: 105,
    minSpeakSeconds: 30,
    record: true,
    evalFocus: ["composure", "brevity", "tone"],
    intro: "Pressure reveals training. Let's train.",
  },
  {
    id: "m-energy-match",
    phase: "main",
    name: "Energy shift",
    skillIds: ["energy-match", "tonality"],
    minutes: 3,
    steps: ["Start at low, tired energy for 20 seconds.", "Lift to warm for 20. Then to electric for 20.", "Same topic throughout."],
    material: { kind: "topic", set: "easy" },
    prepSeconds: 10,
    speakSeconds: 60,
    minSpeakSeconds: 20,
    record: true,
    evalFocus: ["energy range", "control"],
    intro: "Match, then lead. The room follows you.",
  },

  // =====================================================================
  // MAINS — presence
  // =====================================================================
  {
    id: "m-presence-talk",
    phase: "main",
    name: "Body first",
    skillIds: ["gestures", "eye-contact", "stillness", "posture"],
    minutes: 4,
    steps: ["Stand up. Frame from the waist up.", "Spin. 60 seconds. Gesture in the power sphere.", "Eyes on the lens. Feet planted."],
    material: { kind: "topic", set: "easy" },
    prepSeconds: 15,
    speakSeconds: 60,
    minSpeakSeconds: 20,
    record: true,
    evalFocus: ["gestures", "eye contact", "stillness", "posture"],
    intro: "Today I watch your body more than I listen.",
  },
  {
    id: "m-executive",
    phase: "main",
    name: "Executive presence loop",
    skillIds: ["executive-presence", "volume", "pause", "gestures"],
    minutes: 5,
    steps: ["Standing. A leadership prompt appears.", "Volume 7. Two-second pauses. Big gestures.", "Two minutes. Own every second of silence."],
    material: { kind: "story-prompt", set: "leadership" },
    frameworkId: "prep",
    prepSeconds: 45,
    speakSeconds: 120,
    minSpeakSeconds: 40,
    record: true,
    evalFocus: ["presence", "pauses", "volume", "gestures"],
    intro: "Loud, paused, big, steady. That's presence.",
  },

  // =====================================================================
  // MAINS — stage
  // =====================================================================
  {
    id: "m-toast",
    phase: "main",
    name: "The toast",
    skillIds: ["toast", "anecdotes"],
    minutes: 4,
    steps: ["A toast prompt appears. 45 seconds.", "Who, one story, the wish. 60 seconds.", "Raise an imaginary glass at the end."],
    material: { kind: "story-prompt", set: "toast" },
    frameworkId: "toast",
    prepSeconds: 45,
    speakSeconds: 60,
    minSpeakSeconds: 25,
    record: true,
    evalFocus: ["structure", "warmth", "landing"],
    intro: "Sixty seconds everyone remembers.",
  },
  {
    id: "m-throughline",
    phase: "main",
    name: "Throughline talk",
    skillIds: ["throughline", "signposting"],
    minutes: 7,
    steps: ["Spin. Two minutes to write one throughline sentence.", "Three-minute talk. Say it first and last.", "Every section must serve that sentence."],
    material: { kind: "topic", set: "hard" },
    frameworkId: "one-three-one",
    prepSeconds: 120,
    speakSeconds: 180,
    minSpeakSeconds: 60,
    record: true,
    evalFocus: ["throughline", "structure", "callback"],
    intro: "TED talks live or die on one sentence.",
  },
  {
    id: "m-qa-lightning",
    phase: "main",
    name: "Lightning Q&A",
    skillIds: ["qa-lightning", "add"],
    minutes: 4,
    steps: ["Five questions, 25 seconds each.", "Answer first. One detail. Stop.", "Silence between questions is strength."],
    material: { kind: "question", set: "mixed", count: 5, intervalSec: 25 },
    frameworkId: "add",
    prepSeconds: 5,
    speakSeconds: 125,
    minSpeakSeconds: 40,
    record: true,
    evalFocus: ["brevity", "composure", "answer-first"],
    intro: "Fast answers, no rambling. Go.",
  },
  {
    id: "m-five-minute-talk",
    phase: "main",
    name: "Five-minute talk",
    skillIds: ["five-minute-talk", "talk-131", "gestures"],
    minutes: 12,
    steps: ["Standing. Five minutes to prepare 1-3-1.", "Five minutes on camera. No notes.", "Open strong. Three parts. Tie back."],
    material: { kind: "topic", set: "talk" },
    frameworkId: "one-three-one",
    prepSeconds: 300,
    speakSeconds: 300,
    minSpeakSeconds: 120,
    record: true,
    evalFocus: ["structure", "delivery", "presence", "engagement"],
    intro: "A real talk. Everything you've trained, together.",
  },
  {
    id: "m-keynote-10",
    phase: "main",
    name: "Ten-minute keynote",
    skillIds: ["keynote", "story-bank", "vocal-archetypes"],
    minutes: 22,
    steps: ["Ten minutes to prepare. One idea, two stories.", "Ten minutes on camera, standing.", "Friend, motivator, educator, coach, friend."],
    material: { kind: "topic", set: "talk" },
    frameworkId: "one-three-one",
    prepSeconds: 600,
    speakSeconds: 600,
    minSpeakSeconds: 240,
    record: true,
    evalFocus: ["structure", "stories", "vocal archetypes", "presence", "engagement"],
    intro: "This is the stage. Take it.",
  },
  {
    id: "m-signature-talk",
    phase: "main",
    name: "Signature talk",
    skillIds: ["signature-talk", "callbacks", "executive-presence"],
    minutes: 20,
    steps: ["Your talk. The one you could give anywhere.", "Five minutes to set. Eight minutes on camera.", "Callback to your opening in the final line."],
    material: { kind: "story-prompt", set: "signature-talk" },
    frameworkId: "one-three-one",
    prepSeconds: 300,
    speakSeconds: 480,
    minSpeakSeconds: 180,
    record: true,
    evalFocus: ["everything", "callbacks", "presence", "stories"],
    intro: "Elite is a place you visit daily. Welcome.",
  },
];

export const DRILL_MAP: Record<string, Drill> = Object.fromEntries(DRILLS.map((d) => [d.id, d]));
export const WARMUPS = DRILLS.filter((d) => d.phase === "warmup");
export const MAINS = DRILLS.filter((d) => d.phase === "main" && d.id !== "m-baseline");

export function drillsForSkill(skillId: string): Drill[] {
  return DRILLS.filter((d) => d.skillIds.includes(skillId));
}
