import type { Framework } from "./types";

export const FRAMEWORKS: Framework[] = [
  {
    id: "prep",
    name: "PREP",
    short: "Point · Reason · Example · Point",
    steps: [
      { label: "Point", hint: "One sentence. Your answer." },
      { label: "Reason", hint: "Why you believe it." },
      { label: "Example", hint: "One concrete moment that proves it." },
      { label: "Point", hint: "Say it again, shorter." },
    ],
    useWhen: "Any question, opinion, or update.",
    example: "Remote work is better. It cuts commutes. I gained ninety minutes a day. Remote work is better.",
    source: "Toastmasters; taught by Vinh Giang",
  },
  {
    id: "three-two-one",
    name: "3-2-1",
    short: "3 steps · 2 types · 1 thing",
    steps: [
      { label: "Three steps", hint: "How it's done, in order." },
      { label: "Two types", hint: "Two kinds, two ways, two options." },
      { label: "One thing", hint: "The one thing you love, or that matters." },
    ],
    useWhen: "Random topics. Objects. Anything you feel blank about.",
    example: "Avocados: cut, mash, season. Two ways: smashed or like a fruit. One thing: perfect on keto.",
    source: "Vinh Giang",
  },
  {
    id: "what-so-what",
    name: "What / So what / Now what",
    short: "Fact · Why it matters · Next step",
    steps: [
      { label: "What", hint: "The idea or the thing that happened." },
      { label: "So what", hint: "Why it matters to the listener." },
      { label: "Now what", hint: "The action you want." },
    ],
    useWhen: "Updates, feedback, leading people to action.",
    example: "The launch slipped. That costs us the holiday window. Let's cut scope this week.",
    source: "Matt Abrahams, Think Faster, Talk Smarter",
  },
  {
    id: "problem-solution-benefit",
    name: "Problem → Solution → Benefit",
    short: "Pain · Fix · Payoff",
    steps: [
      { label: "Problem", hint: "Make it specific. Make it hurt." },
      { label: "Solution", hint: "The steps, briefly." },
      { label: "Benefit", hint: "What changes for them." },
    ],
    useWhen: "Persuading, pitching, proposing.",
    example: "We lose a day a week to status meetings. Replace them with a written update. Everyone gets Fridays back.",
    source: "Matt Abrahams",
  },
  {
    id: "past-present-future",
    name: "Past / Present / Future",
    short: "Then · Now · Next",
    steps: [
      { label: "Past", hint: "Where this started." },
      { label: "Present", hint: "Where it is now." },
      { label: "Future", hint: "Where it goes, and your take." },
    ],
    useWhen: "Any topic when you feel blank. Time is a free structure.",
    example: "Phones used to make calls. Now they run our lives. Next, they'll disappear into glasses.",
    source: "Classic impromptu structure",
  },
  {
    id: "rule-of-three",
    name: "Rule of three",
    short: "Announce three · deliver three · stop",
    steps: [
      { label: "Announce", hint: "'Three things about…'" },
      { label: "One, two, three", hint: "Number them out loud." },
      { label: "Wrap", hint: "Repeat the three in five words." },
    ],
    useWhen: "Explaining, teaching, listing.",
    example: "Three reasons to walk: it's free, it's daily thinking time, and it fixes your mood.",
    source: "Classical rhetoric",
  },
  {
    id: "contrast",
    name: "Contrast",
    short: "Not this · but that · why",
    steps: [
      { label: "Not this", hint: "The common belief or the wrong answer." },
      { label: "But that", hint: "Your answer, sharply different." },
      { label: "Why", hint: "One reason it's better." },
    ],
    useWhen: "Questions with many possible answers. Sounding decisive.",
    example: "The problem isn't time. It's attention. You have hours; you don't have focus.",
    source: "Yasir Khan, Speak Like a CEO",
  },
  {
    id: "add",
    name: "ADD",
    short: "Answer · Detail · Describe value",
    steps: [
      { label: "Answer", hint: "One sentence. Yes, no, or the number." },
      { label: "Detail", hint: "One example or reason." },
      { label: "Describe", hint: "Why it matters to the asker." },
    ],
    useWhen: "Q&A, interviews, being put on the spot.",
    example: "Yes, we'll ship Friday. Testing finished today. That means you can demo Monday.",
    source: "Matt Abrahams",
  },
  {
    id: "golden-circle",
    name: "Why → How → What",
    short: "Belief · Method · Product",
    steps: [
      { label: "Why", hint: "What you believe. The cause." },
      { label: "How", hint: "The way you do it differently." },
      { label: "What", hint: "The thing itself. Last." },
    ],
    useWhen: "Pitches, introductions, anything you want people to join.",
    example: "I believe practice beats talent. So I train daily, in public. That's why I built this app.",
    source: "Simon Sinek, Start With Why",
  },
  {
    id: "para",
    name: "PARA",
    short: "Point · Action · Result · Ask",
    steps: [
      { label: "Point", hint: "The headline." },
      { label: "Action", hint: "What you did." },
      { label: "Result", hint: "What happened. Numbers help." },
      { label: "Ask", hint: "What you need now." },
    ],
    useWhen: "Updates to a boss, a client, a team.",
    example: "Signups doubled. We rewrote onboarding. Conversion went from 4 to 9 percent. I need two more weeks.",
    source: "Vinh Giang",
  },
  {
    id: "story-formula",
    name: "Story formula",
    short: "Incident · Relive · The reason I'm telling you this",
    steps: [
      { label: "Incident", hint: "When, where, who. One sentence." },
      { label: "Relive it", hint: "Present tense. Dialogue. Senses." },
      { label: "The reason", hint: "'The reason I'm telling you this is…'" },
    ],
    useWhen: "Any story, in any setting. Two to three minutes max.",
    example: "Last March, backstage in Sydney, my hands are shaking. The stage manager says… The reason I'm telling you this is…",
    source: "Vinh Giang",
  },
  {
    id: "story-spine",
    name: "Story spine",
    short: "Once upon a time… until one day… because of that…",
    steps: [
      { label: "Once upon a time", hint: "The world before." },
      { label: "Every day", hint: "The routine." },
      { label: "Until one day", hint: "The thing that broke the routine." },
      { label: "Because of that", hint: "Consequence. Then another." },
      { label: "Until finally", hint: "The climax." },
      { label: "Ever since", hint: "The new normal. The lesson." },
    ],
    useWhen: "Building a story from nothing.",
    example: "Every day I said yes to everything. Until one day I missed my sister's birthday. Because of that…",
    source: "Kenn Adams; popularized by Pixar",
  },
  {
    id: "abt",
    name: "And, But, Therefore",
    short: "Setup · Conflict · Resolution",
    steps: [
      { label: "And", hint: "Facts we agree on, joined by 'and'." },
      { label: "But", hint: "The problem. The twist." },
      { label: "Therefore", hint: "What follows." },
    ],
    useWhen: "Any argument or story in three sentences.",
    example: "We had users and we had revenue. But churn was fifty percent. Therefore we stopped selling and fixed onboarding.",
    source: "Randy Olson",
  },
  {
    id: "sparkline",
    name: "What is / what could be",
    short: "Reality · Possibility · repeat · New bliss",
    steps: [
      { label: "What is", hint: "The current reality." },
      { label: "What could be", hint: "The better future." },
      { label: "Repeat", hint: "Alternate two more times, bigger each time." },
      { label: "New bliss", hint: "The world once the gap is closed." },
    ],
    useWhen: "Inspiring, rallying, big-picture talks.",
    example: "Today we practice alone. Imagine a coach in your pocket. Today feedback takes weeks. Imagine seconds…",
    source: "Nancy Duarte, Resonate",
  },
  {
    id: "monroe",
    name: "Motivated sequence",
    short: "Attention · Need · Satisfaction · Visualization · Action",
    steps: [
      { label: "Attention", hint: "A hook they can't ignore." },
      { label: "Need", hint: "The problem, and why it's theirs." },
      { label: "Satisfaction", hint: "Your solution." },
      { label: "Visualization", hint: "Paint life with it (or without it)." },
      { label: "Action", hint: "One specific thing to do now." },
    ],
    useWhen: "Persuasive talks with a clear ask.",
    example: "Half of you will lose your voice to fear this year… Here's the fix… Picture yourself… Start tonight.",
    source: "Alan Monroe",
  },
  {
    id: "star",
    name: "STAR",
    short: "Situation · Task · Action · Result",
    steps: [
      { label: "Situation", hint: "Context in one line." },
      { label: "Task", hint: "What you had to do." },
      { label: "Action", hint: "What you actually did." },
      { label: "Result", hint: "Numbers if you have them." },
    ],
    useWhen: "Interviews, proving experience.",
    example: "Launch was slipping. I owned the timeline. I cut scope and daily-checked. We shipped a week early.",
    source: "Behavioral interviewing",
  },
  {
    id: "one-three-one",
    name: "1-3-1",
    short: "One idea · three themes · one conclusion",
    steps: [
      { label: "One idea", hint: "Promise it in the first 30 seconds." },
      { label: "Three themes", hint: "Each with a story or proof." },
      { label: "One conclusion", hint: "Tie back to the promise." },
    ],
    useWhen: "Talks of 5 minutes or more.",
    example: "Practice beats talent. Three proofs: voice, structure, stories. So practice today.",
    source: "Keynote structure",
  },
  {
    id: "toast",
    name: "The toast",
    short: "Who · one story · the wish",
    steps: [
      { label: "Who", hint: "Name them and your relationship." },
      { label: "One story", hint: "A single moment that shows who they are." },
      { label: "The wish", hint: "Raise the glass on one sentence." },
    ],
    useWhen: "Weddings, birthdays, farewells.",
    example: "Sam and I met in a broken elevator. Ten minutes in, she was running the meeting. To Sam.",
    source: "Classic toast structure",
  },
  {
    id: "bridge",
    name: "Bridging",
    short: "Acknowledge · bridge · message",
    steps: [
      { label: "Acknowledge", hint: "'That's a fair question.'" },
      { label: "Bridge", hint: "'What matters most here is…'" },
      { label: "Message", hint: "Your point, briefly." },
    ],
    useWhen: "Hostile, off-topic, or trap questions.",
    example: "Fair question. What matters most is whether users stay, and they do: retention is up 30 percent.",
    source: "Media training",
  },
  {
    id: "disagree",
    name: "Disagree gracefully",
    short: "Acknowledge · reframe · offer",
    steps: [
      { label: "Acknowledge", hint: "Name the part that's true." },
      { label: "Reframe", hint: "'I see it differently, because…'" },
      { label: "Offer", hint: "A way forward or a question." },
    ],
    useWhen: "Pushback without a fight.",
    example: "You're right that it's expensive. I see it differently: it's cheaper than another failed launch. Can we pilot it?",
    source: "Negotiation practice",
  },
  {
    id: "eli5",
    name: "Explain simply",
    short: "Simple words · one analogy · one example",
    steps: [
      { label: "Simple words", hint: "No jargon. Short sentences." },
      { label: "One analogy", hint: "'It's like…'" },
      { label: "One example", hint: "A moment they can picture." },
    ],
    useWhen: "Teaching, onboarding, explaining your work.",
    example: "Compound interest is money making babies. Like rabbits. Ten dollars becomes twenty, then forty.",
    source: "Feynman technique",
  },
];

export const FRAMEWORK_MAP: Record<string, Framework> = Object.fromEntries(FRAMEWORKS.map((f) => [f.id, f]));
